// client/src/components/instructor/instructorStudentsList.vue
<template>
    <div v-if="show">
        <h3>Students Enrolled in Selected Course</h3>

        <table class="table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Grade</th>
                </tr>
            </thead>
            <tbody>
                <tr is="instructor-students-row" v-for="enrollment in enrollments" :enrollment="enrollment"></tr>
            </tbody>
        </table>
    </div>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script src="./instructorStudentsList.vue.js"></script>

// client/components/instructor/InstructorStudentsList.tsx
import * as React from 'react';
import InstructorStudentRow from './InstructorStudentRow';

const InstructorStudentsList = ({enrollments, visible}) => {
    let style = visible ? {display: 'block'} : {display: 'none'};
    
    return (
        <div style={style}>
            <h3>Students Enrolled in Selected Course</h3>

            <table className="table">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Grade</th>
                    </tr>
                </thead>
                <tbody>
                    {enrollments.map(enrollment =>
                        <InstructorStudentRow key={enrollment.id} enrollment={enrollment} />
                    )}
                </tbody>
            </table>
        </div>
    );
};

(InstructorStudentsList as any).propTypes = {
    visible: React.PropTypes.bool.isRequired,
    enrollments: React.PropTypes.array.isRequired
};

export default InstructorStudentsList;
