// client/components/department/DepartmentsList.tsx
import * as React from 'react';
import * as _ from 'lodash';
import DepartmentRow from './DepartmentRow';

const DepartmentsList = ({departments, onSaveClick, onDetailsClick, onDeleteClick}) => {
    return (
        <table className="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Budget</th>
                <th>Start Date</th>
                <th>Administrator</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {departments.map(department =>
                <DepartmentRow key={department.id} department={department} 
                               onSaveClick={() => onSaveClick(department.id)}
                               onDetailsClick={() => onDetailsClick(department.id)}
                               onDeleteClick={() => onDeleteClick(department.id)}
                />
            )}
            </tbody>
        </table>
    );
};

(DepartmentsList as any).propTypes = {
    departments: React.PropTypes.array.isRequired,
    onSaveClick: React.PropTypes.func.isRequired, 
    onDetailsClick: React.PropTypes.func.isRequired,
    onDeleteClick: React.PropTypes.func.isRequired
};

export default DepartmentsList;

// client/src/components/department/departmentsList.vue
<template>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Budget</th>
                <th>Start Date</th>
                <th>Administrator</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr is="department-row" v-for="department in departments" :department="department"
                :delete-department-action="deleteDepartmentAction" :department-details-action="departmentDetailsAction"
                :edit-department-action="editDepartmentAction"></tr>
        </tbody>
    </table>

    <simple-confirm :show.sync="showConfirm" :confirm-action.sync="confirmAction"></simple-confirm>
    <department-details :department="department" :show.sync="showDetailsModal"></department-details>
    <department-save :department="department" :show.sync="showEditModal"></department-save>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script src="./departmentsList.vue.js"></script>
