// client/src/components/department/departmentDetails.vue
<template>
    <modal :show.sync="show">
        <div slot="modal-header" class="modal-header">
            <h4 class="modal-title">Department Details</h4>
        </div>
        <div slot="modal-body" class="modal-body">
            <div class="form-horizontal">
                <display-row :label="'Name'" :value="department.name"></display-row>
                <display-row :label="'Budget'" :value="budgetDisplay"></display-row>
                <display-row :label="'Start Date'" :value="startDate"></display-row>
                <display-row :label="'Administrator'" :value="instructorName"></display-row>
            </div>
        </div>
        <div slot="modal-footer" class="modal-footer">
            <button type="button" @click="cancel" class="btn btn-default">Close</button>
        </div>
    </modal>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script src="./departmentDetails.vue.js"></script>

// client/src/components/department/DepartmentDetails.tsx
import * as React from 'react';
import {connect} from 'react-redux';
import {Modal, Button} from 'react-bootstrap';
import * as _ from 'lodash';
import DisplayRow from '../common/DisplayRow';
import dateFormatter from '../../formatters/dateFormatter';
import currencyFormatter from '../../formatters/currencyFormatter';

class DepartmentDetails extends React.Component<any, any> {
    constructor(props) {
        super(props);

        this.state = {
            department: _.assign({}, props.department),
            visible: props.visible,
            close: props.close
        };
    }

    render() {
        let department = this.props.department;
        let instructor = department.instructor;
        let instructorName = instructor ? `${instructor.lastName}, ${instructor.firstName}` : '';
        let startDate = dateFormatter.date(department.startDate);
        let budgetDisplay = currencyFormatter.money(department.budget);

        return (
            <div>
                <Modal show={this.props.visible} onHide={this.props.close}>
                    <Modal.Header closeButton onClick={this.props.close}>
                        <Modal.Title>Department Details</Modal.Title>
                    </Modal.Header>
                    <Modal.Body>
                        <div className="form-horizontal">
                            <DisplayRow label="Name" value={department.name} />

                            <DisplayRow label="Budget" value={budgetDisplay} />

                            <DisplayRow label="Start Date" value={startDate} />

                            <DisplayRow label="Administrator" value={instructorName} />
                        </div>
                    </Modal.Body>
                    <Modal.Footer>
                        <Button onClick={this.props.close}>Close</Button>
                    </Modal.Footer>
                </Modal>
            </div>
        );
    }
}

(DepartmentDetails as any).propTypes = {
    department: React.PropTypes.object.isRequired,
    visible: React.PropTypes.bool.isRequired,
    close: React.PropTypes.func.isRequired
};

function mapStateToProps(state) {
    return {
        department: _.cloneDeep(state.department.current)
    };
}

export default connect(mapStateToProps)(DepartmentDetails);
