// client/src/components/Navigation.tsx
import * as React from 'react';
import {IndexLink } from 'react-router';
import {Navbar, Nav, NavItem} from 'react-bootstrap';
import { LinkContainer, IndexLinkContainer } from 'react-router-bootstrap';

class Navigation extends React.Component<any, any> {
    render() {
        return (
            <Navbar inverse fixedTop>
                <Navbar.Header>
                    <Navbar.Brand>
                        <IndexLink to="/" className="navbar-brand">Contoso University</IndexLink>
                    </Navbar.Brand>
                    <Navbar.Toggle />
                </Navbar.Header>

                <Navbar.Collapse>
                    <Nav>
                        <IndexLinkContainer to="/">
                            <NavItem eventKey={1}>Home</NavItem>
                        </IndexLinkContainer>

                        <LinkContainer to="/about">
                            <NavItem eventKey={2}>About</NavItem>
                        </LinkContainer>

                        <LinkContainer to="/students">
                            <NavItem eventKey={3}>Students</NavItem>
                        </LinkContainer>

                        <LinkContainer to="/courses">
                            <NavItem eventKey={4}>Courses</NavItem>
                        </LinkContainer>

                        <LinkContainer to="/instructors">
                            <NavItem eventKey={5}>Instructors</NavItem>
                        </LinkContainer>

                        <LinkContainer to="/departments">
                            <NavItem eventKey={6}>Departments</NavItem>
                        </LinkContainer>
                    </Nav>
                    <Nav pullRight>
                        <NavItem eventKey={1} href="/logout">LogOut   <i className="fa fa-sign-out fa-lg"></i></NavItem>
                    </Nav>
                </Navbar.Collapse>
            </Navbar>
        );
    }
}

export default Navigation;

// client/src/components/navigation.vue
<template>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand navbar-brand" href="/">Contoso University</a>

                <button type="button" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span><span class="icon-bar"></span>
                </button>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li role="presentation" class="active">
                        <a v-link="{ name: 'home'}" class="nav">Home</a>
                    </li>
                    <li role="presentation">
                        <a v-link="{ name: 'about'}" class="nav">About</a>
                    </li>
                    <li role="presentation">
                        <a v-link="{ name: 'students'}" class="nav">Students</a>
                    </li>
                    <li role="presentation">
                        <a v-link="{ name: 'courses'}" class="nav">Courses</a>
                    </li>
                    <li role="presentation">
                        <a v-link="{ name: 'instructors'}" class="nav">Instructors</a>
                    </li>
                    <li role="presentation">
                        <a v-link="{ name: 'departments'}" class="nav">Departments</a>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li role="presentation" class="">
                        <a href="/logout">LogOut <i class="fa fa-sign-out fa-lg"></i></a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script></script>
