// client/src/components/instructor/instructorRow.vue
<template>
    <tr :class="{'success': active}">
        <td>{{instructor.lastName}}</td>
        <td>{{instructor.firstName}}</td>
        <td>{{hireDateDisplay}}</td>
        <td>{{office}}</td>
        <td>
            <div v-for="course in instructor.courses">{{course.number}}&nbsp;{{course.title}}</div>
        </td>
        <td class="tools">
            <a href="#" @click="selectInstructor"><i class="fa fa-hand-o-up fa-lg"></i></a>

            <a href="#" @click="showEdit"><i class="fa fa-pencil fa-lg"></i></a>

            <a href="#" @click="showDetails"><i class="fa fa-info fa-lg"></i></a>

            <a href="#" @click="deleteInstructor"><i class="fa fa-trash-o fa-lg"></i></a>
        </td>
    </tr>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script src="./instructorRow.vue.js"></script>

// client/src/components/instructor/InstructorRow.tsx
import * as React from 'react';
import dateFormatter from '../../formatters/dateFormatter';

const InstructorRow = (props) => {
    let instructor = props.instructor;

    let office = instructor.officeAssignment ? instructor.officeAssignment.location : '';
    let hireDateDisplay = dateFormatter.date(instructor.hireDate);

    let activeClass = props.selectedInstructorId === instructor.id ? 'success' : '';

    return (
        <tr className={activeClass}>
            <td>{instructor.lastName}</td>
            <td>{instructor.firstName}</td>
            <td>{hireDateDisplay}</td>
            <td>{office}</td>
            <td>{instructor.courses.map(course =>
                <div key={course.id}>{course.number}&nbsp;{course.title}</div>
            )}
            </td>
            <td className="tools">
                <a href="#" onClick={props.onSelectClick}><i className="fa fa-hand-o-up fa-lg"></i></a>

                <a href="#" onClick={props.onSaveClick}><i className="fa fa-pencil fa-lg"></i></a>

                <a href="#" onClick={props.onDetailsClick}><i className="fa fa-info fa-lg"></i></a>

                <a href="#" onClick={props.onDeleteClick}><i className="fa fa-trash-o fa-lg"></i></a>
            </td>
        </tr>
    );
};

(InstructorRow as any).propTypes = {
    instructor: React.PropTypes.object.isRequired,
    selectedInstructorId: React.PropTypes.number.isRequired,
    onSelectClick: React.PropTypes.func.isRequired,
    onSaveClick: React.PropTypes.func.isRequired,
    onDetailsClick: React.PropTypes.func.isRequired,
    onDeleteClick: React.PropTypes.func.isRequired
};

export default InstructorRow;
