// client/src/components/student/StudentEnrollmentsList.tsx
import * as React from 'react';
import StudentEnrollmentsRow from './StudentEnrollmentsRow';

const StudentEnrollmentsList = ({enrollments}) => {
    return (
        <table className="table">
            <thead>
            <tr>
                <th>Course Title</th>
                <th>Grade</th>
            </tr>
            </thead>
            <tbody>
                {enrollments.map(enrollment =>
                    <StudentEnrollmentsRow key={enrollment.id} enrollment={enrollment} />
                )}
            </tbody>
        </table>
    );
};

(StudentEnrollmentsList as any).propTypes = {
    enrollments: React.PropTypes.array.isRequired
};

export default StudentEnrollmentsList;

// client/src/components/student/studentEnrollmentsList.vue
<template>
    <table class="table">
        <thead>
            <tr>
                <th>Course Title</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody>
            <tr is="student-enrollments-row" v-for="enrollment in enrollments" :enrollment="enrollment"></tr>
        </tbody>
    </table>
</template>
<style lang="less" rel="stylesheet/less">

</style>
<script src="./studentEnrollmentsList.vue.js"></script>
